version: '3.8'
services:

  ubuntu:
    build:
      context: ./compose/ubuntu/
      dockerfile: Dockerfile
    networks:
      - model-network
    volumes:
      - "./compose:/work/"
#      - "${LOCAL_DATA_PATH}:/data/"
    ports:
      - 8888:8888
    tty: true
    command: /bin/bash

  postgres:
    image: postgres:9.6  #check version
    environment:
      - POSTGRES_USER=airflow
      - POSTGRES_PASSWORD=airflow
      - POSTGRES_DB=airflow
      - PGDATA=/tmp
    ports:
      - 5432:5432
    volumes:
      - ./postgres-data:/var/lib/postgresql/data:rw
    healthcheck: #new
      test: ["CMD", "pg_isready", "-U", "airflow"]
      interval: 5s
      retries: 5
    restart: always  #new
    networks:
      - model-network
    logging:
      options:
        max-size: 10m
        max-file: "3"

  webserver:
    image: puckel/docker-airflow:1.10.9
    user: root
    restart: always
    depends_on:
      - postgres
    environment:
      - LOAD_EX=y
      - EXECUTOR=Local
    networks:
      - model-network
    logging:
      options:
        max-size: 10m
        max-file: "3"
    volumes:
      - ./dags:/usr/local/airflow/dags # host:container
#      - ./compose/ubuntu/requirements.txt:/requirements.txt
#      - "./:/work/"
#      - "${LOCAL_DATA_PATH}:/data/"
      - ./configs:/usr/local/airflow/configs # host:container
    ports:
      - 8080:8080 # host:container
#    command: bash -c "pip install /work/" && webserver
    command: webserver
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost:8080/health"]
      interval: 10s
      timeout: 10s
      retries: 5
    restart: always

networks:
  model-network:

